export const marketingKeys: string[] = [
  "enable_optional_tracking",
  "ga4_measurement_id",
  "google_ads_conversion_id",
  "google_ads_conversion_label",
  "google_search_console_verification",
  "bing_webmaster_verification",
  "yandex_verification",
  "baidu_verification",
  "pinterest_verification",
  "facebook_domain_verification",
  "default_og_image",
  "twitter_handle",
  "twitter_creator",
  "facebook_app_id",
];
